from src.fewshot_util import generate_no_verbatim

prompt = """200 different ways to prompt a language model to evaluate whether a sentence has positive or negative sentiment:
"Tell if the sentiment of the sentence is positive or negative.",
"Indicate if the sentence's sentiment is positive or negative.",
"Clarify if the sentiment of the sentence is positive or negative.",
"Sentiment analysis task (positive/negative)",
"English Reading Comprehension Exam: Identify whether the following sentences are positive or negative in sentiment.",
"College Preparatory Exam (Reading Comprehension): Identify whether the following sentences are positive or negative in sentiment.",
"College Preparatory Exam (Reading Comprehension): Identify whether the following sentences are positive or negative in sentiment.",
"Could you tell me if the sentiment of the sentence is positive or negative?",
"Are you able to tell me if the sentiment of the sentence is positive or negative?",
"I want to know if the sentiment of the sentence is positive or negative.",
"You are an expert at telling if the sentiment of a sentence is positive or negative",
"You are a master at finding if a sentence's sentiment is negative or positive",
"Would you be a dear and tell me if the sentiment of the sentence is positive or negative?",
"Can you tell me if the sentiment of the sentence is positive or negative?","""

prompt2 = """"College Preparatory Exam (Reading Comprehension): Answer whether the following sentences are negative or positive in sentiment.",
"I want to learn whether the sentiment of this sentence is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Tell whether the sentiment of the following sentence is negative or positive.",
"Could you be a dear and check whether the sentiment of the sentence is positive or negative?",
"You are a master at telling whether the sentiment of a sentence is positive or negative",
"English Reading Comprehension Exam: Tell whether the following sentences are positive or negative in sentiment.",
"Reading Comprehension Exam: Tell whether the sentence is positive or negative in sentiment.",
"Are you able to check if the sentence's sentiment is negative or positive?",
"Would you be a dear and check whether the sentence's sentiment is positive or negative?",
"I want to know whether the sentiment of the sentence is positive or negative.",
"I want to learn if this sentence's sentiment is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Tell whether the sentiment of the following sentence is positive or negative.",
"Clarify if the sentence's sentiment is negative or positive.",
"English Reading Comprehension Exam: Identify whether the sentiment of the following sentences is negative or positive.",
"Tell if the sentiment is negative or positive.",
"Sentiment (negative/positive) understanding task",
"Could you be a dear and tell me if the sentiment of this sentence is positive or negative?",
"Reading Comprehension Exam: Identify whether the sentence is negative or positive in sentiment.",
"I want to know whether the sentence's sentiment is negative or positive.",
"Be a dear and tell me whether the sentiment of this sentence is negative or positive, will you?",
"Analysis of sentiment task (positive/negative)",
"Clarify if the sentiment of this sentence is positive or negative.",
"Indicate if the sentiment of this sentence is positive or negative.",
"I want to find out if the sentence's sentiment is positive or negative.",
"Could you tell me if this sentence's sentiment is positive or negative?",
"I've heard you can tell whether the sentiment of a sentence is positive or negative."
"Tell whether the sentence is positive or negative.",
"I need to know whether the sentiment of this sentence is negative or positive.",
"English Reading Comprehension Exam: Tell whether the sentence is negative or positive in sentiment.",
"English Reading Comprehension Exam: Answer whether the following sentences are positive or negative in sentiment.",
"Someone told me you can tell whether a sentence's sentiment is negative or positive."
"Reading Comprehension Exam: Answer whether the following sentence is negative or positive in sentiment.",
"College Preparatory Exam (Reading Comprehension): Answer whether the following sentence is negative or positive in sentiment.",
"Are you able to check whether the sentiment of this sentence is positive or negative?",
"Tell me the sentence's sentiment!",
"Would you be a dear and tell me if the sentence's sentiment is negative or positive?",
"English Reading Comprehension Exam: Tell whether the sentiment of the sentence is negative or positive.",
"I need to know whether the sentence's sentiment is negative or positive.",
"You are a master at telling if the sentiment of a sentence is negative or positive",
"You are a master at telling if a sentence's sentiment is negative or positive",
"Be a dear and check whether this sentence's sentiment is negative or positive, will you?",
"Tell me the sentiment of the sentence!",
"College Preparatory Exam (Reading Comprehension): Tell whether the sentiment of the following sentences is negative or positive.",
"College Preparatory Exam (Reading Comprehension): Identify whether the sentences are negative or positive in sentiment.",
"English Reading Comprehension Exam: Identify whether the sentiment of the sentences is positive or negative.",
"Indicate whether the sentiment of the sentence is positive or negative.",
"I need to learn whether the sentiment of this sentence is positive or negative.",
"I want to learn whether the sentence's sentiment is negative or positive.",
"Reading Comprehension Exam: Identify whether the sentences are negative or positive in sentiment.",
"Reading Comprehension Exam: Answer whether the sentence is negative or positive in sentiment.",
"I want to find out if this sentence's sentiment is positive or negative.",
"Indicate whether the sentiment of the sentence is negative or positive.",
"You are a genius at finding whether the sentiment of a sentence is negative or positive",
"You are a genius at finding if a sentence's sentiment is positive or negative",
"Indicate whether the sentence is positive or negative.",
"Could you be a dear and tell me if the sentence's sentiment is positive or negative?",
"Would you be a dear and check whether the sentiment of the sentence is negative or positive?",
"Would you be a dear and check if the sentence's sentiment is positive or negative?",
"Someone told me you can find out if the sentiment of a sentence is positive or negative."
"I've heard you're really good at finding out if the sentiment of a sentence is positive or negative."
"Be a dear and check if this sentence's sentiment is negative or positive, will you?",
"Reading Comprehension Exam: Answer whether the following sentences are negative or positive in sentiment.",
"Reading Comprehension Exam: Tell whether the sentiment of the following sentence is negative or positive.",
"You are a master at finding if a sentence's sentiment is negative or positive",
"Reading Comprehension Exam: Tell whether the following sentence is negative or positive in sentiment.",
"You are an expert at telling if a sentence's sentiment is negative or positive",
"Indicate whether the sentiment is positive or negative.",
"Would you be a dear and check whether the sentiment of this sentence is negative or positive?",
"College Preparatory Exam (Reading Comprehension): Answer whether the sentiment of the following sentence is positive or negative.",
"Just tell me if the sentiment is negative or positive!",
"Be a dear and check whether the sentiment of this sentence is positive or negative, will you?",
"I need to know if the sentiment of this sentence is positive or negative.",
"You are an expert at telling whether the sentiment of a sentence is negative or positive",
"Reading Comprehension Exam: Tell whether the sentiment of the following sentences is negative or positive.",
"Clarify if the sentence's sentiment is positive or negative.",
"Comprehension of sentiment (positive/negative) task",
"Reading Comprehension Exam: Answer whether the following sentences are positive or negative in sentiment.",
"Can you tell me if the sentiment of this sentence is negative or positive?",
"College Preparatory Exam (Reading Comprehension): Tell whether the sentiment of the following sentences is positive or negative.",
"Be a dear and tell me if the sentiment of this sentence is negative or positive, will you?",
"Are you able to check whether the sentiment of this sentence is negative or positive?",
"You are a genius at telling whether a sentence's sentiment is negative or positive",
"I need to learn if the sentence's sentiment is positive or negative.",
"Would you be a dear and tell me if the sentence's sentiment is positive or negative?",
"I want to find out whether the sentence's sentiment is positive or negative.",
"You are an expert at telling if a sentence's sentiment is positive or negative",
"Are you able to tell me if the sentiment of this sentence is negative or positive?",
"Tell if the sentence is positive or negative.",
"You are an expert at telling whether the sentiment of a sentence is positive or negative",
"English Reading Comprehension Exam: Tell whether the sentiment of the following sentence is positive or negative.",
"I want to learn whether the sentiment of the sentence is negative or positive.",
"Could you be a dear and check whether the sentiment of the sentence is negative or positive?",
"Tell whether the sentence's sentiment is positive or negative.",
"Sentiment analysis task (positive/negative)",
"English Reading Comprehension Exam: Identify whether the sentiment of the sentences is negative or positive.",
"Are you able to tell me if the sentence's sentiment is positive or negative?",
"Understanding of sentiment task (negative/positive)",
"Are you able to check if the sentence's sentiment is positive or negative?",
"You are a master at finding whether a sentence's sentiment is positive or negative",
"English Reading Comprehension Exam: Answer whether the sentiment of the following sentence is negative or positive.",
"Could you tell me if the sentiment of the sentence is positive or negative?",
"Are you able to tell me if the sentence's sentiment is negative or positive?",
"Tell me if the sentence is negative or positive!",
"I need to know whether the sentiment of this sentence is positive or negative.",
"I need to know if the sentence's sentiment is negative or positive.",
"Tell whether this sentence's sentiment is negative or positive.",
"I want to know if the sentiment of this sentence is positive or negative.",
"English Reading Comprehension Exam: Identify whether the sentiment of the sentence is negative or positive.",
"Be a dear and check if the sentence's sentiment is negative or positive, will you?",
"Someone told me you can tell if the sentiment of a sentence is positive or negative."
"Just tell me the sentiment of this sentence!",
"I want to learn if the sentence's sentiment is negative or positive.",
"English Reading Comprehension Exam: Answer whether the sentiment of the sentences is positive or negative.",
"Clarify whether the sentiment is negative or positive.",
"I've heard you can tell if the sentiment of a sentence is negative or positive."
"Could you tell me whether the sentiment of this sentence is positive or negative?",
"Reading Comprehension Exam: Identify whether the sentiment of the sentences is negative or positive.",
"Reading Comprehension Exam: Identify whether the sentiment of the sentence is negative or positive.",
"Would you be a dear and tell me whether the sentiment of this sentence is positive or negative?",
"You are a genius at telling if the sentiment of a sentence is positive or negative",
"Reading Comprehension Exam: Identify whether the sentiment of the sentences is positive or negative.",
"English Reading Comprehension Exam: Identify whether the following sentence is negative or positive in sentiment.",
"Could you check if the sentiment of this sentence is negative or positive?",
"Could you be a dear and check if the sentiment of this sentence is negative or positive?",
"Reading Comprehension Exam: Tell whether the sentiment of the following sentences is positive or negative.",
"Sentiment (positive/negative) understanding task",
"I need to know if the sentiment of the sentence is positive or negative.",
"Reading Comprehension Exam: Answer whether the following sentence is positive or negative in sentiment.",
"You are an expert at finding whether a sentence's sentiment is negative or positive",
"You are an expert at telling whether a sentence's sentiment is negative or positive",
"You are a master at finding if a sentence's sentiment is positive or negative",
"I need to learn whether the sentence's sentiment is negative or positive.",
"Reading Comprehension Exam: Identify whether the sentiment of the sentence is positive or negative.",
"Tell whether the sentiment of this sentence is negative or positive.",
"Reading Comprehension Exam: Answer whether the sentiment of the following sentence is positive or negative.",
"Tell whether this sentence's sentiment is positive or negative.",
"I've heard you can find out whether a sentence's sentiment is negative or positive."
"Indicate whether this sentence's sentiment is positive or negative.",
"Just tell me if the sentiment is positive or negative!",
"Someone told me you can find out whether the sentiment of a sentence is negative or positive."
"Indicate whether the sentiment is negative or positive.",
"Would you be a dear and check whether the sentiment of this sentence is positive or negative?",
"Sentiment comprehension (negative/positive) task",
"I want to learn whether this sentence's sentiment is negative or positive.",
"I need to know if the sentiment of the sentence is negative or positive.",
"Clarify whether the sentiment of this sentence is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Tell whether the sentiment of the sentence is negative or positive.",
"Would you be a dear and tell me whether the sentiment of this sentence is negative or positive?",
"I've heard you're really good at telling if a sentence's sentiment is positive or negative."
"You are an expert at finding if a sentence's sentiment is negative or positive",
"I want to learn whether the sentiment of the sentence is positive or negative.",
"Tell whether the sentiment of the sentence is negative or positive.",
"Be a dear and tell me whether the sentence's sentiment is positive or negative, will you?",
"I want to find out whether this sentence's sentiment is positive or negative.",
"Sentiment (positive/negative) analysis task",
"College Preparatory Exam (Reading Comprehension): Tell whether the following sentences are positive or negative in sentiment.",
"Clarify if the sentence is positive or negative.",
"Someone told me you can find out whether a sentence's sentiment is positive or negative."
"I want to find out if the sentence's sentiment is negative or positive.",
"College Preparatory Exam (Reading Comprehension): Answer whether the sentiment of the sentence is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Answer whether the sentences are positive or negative in sentiment.",
"Someone told me you can find out whether a sentence's sentiment is negative or positive."
"You are an expert at telling whether a sentence's sentiment is positive or negative",
"I've heard you can tell whether a sentence's sentiment is negative or positive."
"College Preparatory Exam (Reading Comprehension): Identify whether the following sentences are positive or negative in sentiment.",
"Understanding of sentiment task (positive/negative)",
"Reading Comprehension Exam: Answer whether the sentiment of the sentences is negative or positive.",
"Could you tell me if the sentiment of the sentence is negative or positive?",
"You are a genius at finding whether a sentence's sentiment is positive or negative",
"Reading Comprehension Exam: Tell whether the following sentences are negative or positive in sentiment.",
"Be a dear and tell me if the sentence's sentiment is positive or negative, will you?",
"Would you be a dear and tell me if the sentiment of the sentence is negative or positive?",
"Someone told me you can tell whether a sentence's sentiment is positive or negative."
"Are you able to tell me whether the sentiment of the sentence is negative or positive?",
"Are you able to tell me if this sentence's sentiment is negative or positive?",
"You are a genius at finding if the sentiment of a sentence is negative or positive",
"Be a dear and tell me if the sentiment of the sentence is negative or positive, will you?",
"Someone told me you can tell if a sentence's sentiment is positive or negative."
"Sentiment understanding task (negative/positive)",
"Clarify if the sentiment of this sentence is negative or positive.",
"English Reading Comprehension Exam: Identify whether the following sentences are positive or negative in sentiment.",
"Can you check whether this sentence's sentiment is negative or positive?",
"I need to find out if the sentence's sentiment is negative or positive.",
"Tell whether the sentiment of the sentence is positive or negative.",
"Clarify whether the sentiment is positive or negative.",
"Are you able to tell me if this sentence's sentiment is positive or negative?",
"I need to find out whether the sentiment of the sentence is negative or positive.",
"Would you be a dear and check if the sentiment of this sentence is positive or negative?",
"College Preparatory Exam (Reading Comprehension): Tell whether the sentiment of the sentences is positive or negative.",
"Can you tell me whether this sentence's sentiment is negative or positive?",
"You are an expert at finding if the sentiment of a sentence is negative or positive",
"I need to know whether this sentence's sentiment is positive or negative.",
"Are you able to tell me whether this sentence's sentiment is negative or positive?",
"You are a master at telling if a sentence's sentiment is positive or negative",
"Reading Comprehension Exam: Tell whether the following sentences are positive or negative in sentiment.",
"Understanding of sentiment (positive/negative) task",
"Are you able to tell me if the sentiment of this sentence is positive or negative?",
"Would you be a dear and tell me whether this sentence's sentiment is positive or negative?",
"I've heard you can find out whether the sentiment of a sentence is positive or negative."
"I want to know if the sentence's sentiment is negative or positive.",
"Can you tell me if the sentence's sentiment is negative or positive?",
"Analysis (positive/negative) of sentiment task",
"Comprehension of sentiment (negative/positive) task",
"I need to know if this sentence's sentiment is positive or negative.",
"Can you tell me whether the sentiment of the sentence is negative or positive?",
"English Reading Comprehension Exam: Tell whether the sentiment of the sentence is positive or negative.",
"Comprehension of sentiment task (negative/positive)",
"I need to learn if the sentiment of this sentence is negative or positive.",
"Can you tell me whether the sentiment of this sentence is positive or negative?",
"Are you able to check if the sentiment of this sentence is negative or positive?",
"Indicate whether the sentence's sentiment is negative or positive.",
"Be a dear and check whether the sentiment of this sentence is negative or positive, will you?",
"Be a dear and check if the sentiment of the sentence is positive or negative, will you?",
"I want to learn if this sentence's sentiment is negative or positive.",
"English Reading Comprehension Exam: Tell whether the following sentences are negative or positive in sentiment.",
"English Reading Comprehension Exam: Tell whether the sentiment of the sentences is positive or negative.",
"Reading Comprehension Exam: Identify whether the sentiment of the following sentence is positive or negative.",
"Could you tell me if the sentiment of this sentence is negative or positive?",
"Reading Comprehension Exam: Identify whether the sentence is positive or negative in sentiment.",
"College Preparatory Exam (Reading Comprehension): Tell whether the following sentence is negative or positive in sentiment.",
"I've heard you're really good at finding out whether the sentiment of a sentence is positive or negative."
"I've heard you can tell whether the sentiment of a sentence is negative or positive."
"Could you be a dear and tell me if this sentence's sentiment is negative or positive?",
"Can you tell me whether the sentiment of this sentence is negative or positive?",
"Could you be a dear and check if the sentiment of this sentence is positive or negative?",
"Someone told me you can find out if a sentence's sentiment is positive or negative."
"English Reading Comprehension Exam: Answer whether the sentiment of the sentences is negative or positive.",
"College Preparatory Exam (Reading Comprehension): Answer whether the sentiment of the sentences is positive or negative.",
"I've heard you can tell if the sentiment of a sentence is positive or negative."
"You are a master at telling if the sentiment of a sentence is positive or negative",
"Reading Comprehension Exam: Tell whether the following sentence is positive or negative in sentiment.",
"Tell if the sentence's sentiment is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Identify whether the following sentences are negative or positive in sentiment.",
"Can you tell me whether the sentiment of the sentence is positive or negative?",
"Analysis (negative/positive) of sentiment task",
"I want to learn if the sentiment of the sentence is positive or negative.",
"Reading Comprehension Exam: Identify whether the following sentence is negative or positive in sentiment.",
"Sentiment analysis (positive/negative) task",
"I want to know if the sentence's sentiment is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Tell whether the following sentences are negative or positive in sentiment.",
"Are you able to tell me whether the sentiment of the sentence is positive or negative?",
"I've heard you can find out if the sentiment of a sentence is negative or positive."
"Could you be a dear and check whether the sentence's sentiment is positive or negative?",
"Just tell me the sentence's sentiment!",
"I want to find out if the sentiment of the sentence is positive or negative.",
"I need to know whether the sentence's sentiment is positive or negative.",
"Someone told me you can find out if a sentence's sentiment is negative or positive."
"College Preparatory Exam (Reading Comprehension): Identify whether the sentence is negative or positive in sentiment.",
"Just tell me the sentiment!",
"Can you check whether the sentiment of this sentence is positive or negative?",
"English Reading Comprehension Exam: Identify whether the sentence is positive or negative in sentiment.",
"Would you be a dear and check whether this sentence's sentiment is negative or positive?",
"Are you able to check whether the sentiment of the sentence is negative or positive?",
"Be a dear and tell me if the sentiment of the sentence is positive or negative, will you?",
"Could you check whether the sentiment of the sentence is positive or negative?",
"I want to know if the sentiment of this sentence is negative or positive.",
"I want to find out whether the sentiment of the sentence is positive or negative.",
"I need to know whether the sentiment of the sentence is negative or positive.",
"Could you be a dear and tell me whether the sentence's sentiment is positive or negative?",
"Could you check if this sentence's sentiment is negative or positive?",
"Could you check if the sentence's sentiment is positive or negative?",
"Could you tell me if the sentiment of this sentence is positive or negative?",
"Clarify whether the sentence's sentiment is positive or negative.",
"Are you able to tell me whether the sentence's sentiment is positive or negative?",
"Could you tell me whether this sentence's sentiment is negative or positive?",
"Clarify if the sentence is negative or positive.",
"I want to know if this sentence's sentiment is negative or positive.",
"Reading Comprehension Exam: Answer whether the sentiment of the following sentence is negative or positive.",
"I need to find out whether the sentiment of the sentence is positive or negative.",
"Could you be a dear and check if this sentence's sentiment is positive or negative?",
"Be a dear and check whether the sentiment of the sentence is positive or negative, will you?",
"Reading Comprehension Exam: Tell whether the sentences are negative or positive in sentiment.",
"Could you check whether this sentence's sentiment is negative or positive?",
"Could you tell me whether the sentence's sentiment is negative or positive?",
"English Reading Comprehension Exam: Tell whether the sentiment of the following sentence is negative or positive.",
"Be a dear and check whether this sentence's sentiment is positive or negative, will you?",
"Can you check whether this sentence's sentiment is positive or negative?",
"Be a dear and tell me whether the sentence's sentiment is negative or positive, will you?",
"Are you able to check if this sentence's sentiment is positive or negative?",
"Tell if the sentiment of the sentence is negative or positive.",
"College Preparatory Exam (Reading Comprehension): Identify whether the sentiment of the sentences is positive or negative.",
"Can you tell me if the sentiment of the sentence is negative or positive?",
"Would you be a dear and check whether the sentiment of the sentence is positive or negative?",
"Tell me this sentence's sentiment!",
"I need to find out whether the sentence's sentiment is positive or negative.",
"Are you able to tell me whether this sentence's sentiment is positive or negative?",
"Could you be a dear and check if this sentence's sentiment is negative or positive?",
"Can you check whether the sentiment of this sentence is negative or positive?",
"Would you be a dear and tell me whether the sentiment of the sentence is positive or negative?",
"You are an expert at telling if the sentiment of a sentence is positive or negative",
"Tell me the sentiment of this sentence!",
"English Reading Comprehension Exam: Answer whether the sentence is positive or negative in sentiment.",
"Comprehension of sentiment task (positive/negative)",
"You are a genius at finding if the sentiment of a sentence is positive or negative",
"Sentiment understanding (negative/positive) task",
"English Reading Comprehension Exam: Identify whether the following sentences are negative or positive in sentiment.",
"Indicate if this sentence's sentiment is positive or negative.",
"Would you be a dear and tell me if the sentiment of this sentence is negative or positive?",
"College Preparatory Exam (Reading Comprehension): Identify whether the following sentence is positive or negative in sentiment.",
"Be a dear and tell me whether the sentiment of the sentence is positive or negative, will you?",
"College Preparatory Exam (Reading Comprehension): Identify whether the sentences are positive or negative in sentiment.",
"English Reading Comprehension Exam: Identify whether the sentiment of the following sentences is positive or negative.",
"English Reading Comprehension Exam: Answer whether the sentences are positive or negative in sentiment.",
"Tell whether the sentiment is negative or positive.",
"Indicate whether this sentence's sentiment is negative or positive.",
"You are an expert at finding whether the sentiment of a sentence is negative or positive",
"Indicate if the sentiment of the sentence is positive or negative.",
"Would you be a dear and check whether this sentence's sentiment is positive or negative?",
"English Reading Comprehension Exam: Tell whether the sentences are positive or negative in sentiment.",
"Analysis of sentiment task (negative/positive)",
"English Reading Comprehension Exam: Tell whether the following sentence is negative or positive in sentiment.",
"Would you be a dear and check if the sentiment of this sentence is negative or positive?",
"English Reading Comprehension Exam: Answer whether the sentiment of the following sentences is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Identify whether the sentiment of the following sentence is positive or negative.",
"I want to learn whether the sentence's sentiment is positive or negative.",
"I want to learn whether the sentiment of this sentence is negative or positive.",
"College Preparatory Exam (Reading Comprehension): Identify whether the sentiment of the sentences is negative or positive.",
"Someone told me you can tell whether the sentiment of a sentence is negative or positive."
"College Preparatory Exam (Reading Comprehension): Answer whether the sentences are negative or positive in sentiment.",
"Could you tell me whether the sentence's sentiment is positive or negative?",
"Tell me if the sentiment is positive or negative!",
"Be a dear and check whether the sentiment of the sentence is negative or positive, will you?",
"Can you check whether the sentence's sentiment is negative or positive?",
"Could you check if the sentiment of the sentence is positive or negative?",
"I need to learn if the sentiment of this sentence is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Answer whether the following sentence is positive or negative in sentiment.",
"I've heard you're really good at telling if a sentence's sentiment is negative or positive."
"I need to learn whether the sentiment of the sentence is negative or positive.",
"I want to find out whether this sentence's sentiment is negative or positive.",
"English Reading Comprehension Exam: Tell whether the sentiment of the following sentences is positive or negative.",
"Could you be a dear and tell me whether the sentiment of the sentence is negative or positive?",
"Reading Comprehension Exam: Tell whether the sentence is negative or positive in sentiment.",
"English Reading Comprehension Exam: Tell whether the sentiment of the sentences is negative or positive.",
"Would you be a dear and tell me if the sentiment of this sentence is positive or negative?",
"English Reading Comprehension Exam: Identify whether the sentence is negative or positive in sentiment.",
"College Preparatory Exam (Reading Comprehension): Answer whether the sentence is negative or positive in sentiment.",
"Could you check if this sentence's sentiment is positive or negative?",
"Could you be a dear and tell me if the sentiment of the sentence is positive or negative?",
"Can you check if the sentence's sentiment is positive or negative?",
"I've heard you're really good at telling if the sentiment of a sentence is negative or positive."
"Could you tell me whether the sentiment of the sentence is positive or negative?",
"Could you be a dear and tell me whether this sentence's sentiment is positive or negative?",
"Could you be a dear and tell me whether the sentiment of the sentence is positive or negative?",
"I want to know if this sentence's sentiment is positive or negative.",
"I've heard you're really good at telling whether the sentiment of a sentence is negative or positive."
"Could you be a dear and tell me if the sentiment of this sentence is negative or positive?",
"You are a master at finding whether the sentiment of a sentence is positive or negative",
"I need to learn whether the sentiment of this sentence is negative or positive.",
"Would you be a dear and tell me if the sentiment of the sentence is positive or negative?",
"You are a master at telling whether a sentence's sentiment is negative or positive",
"You are a genius at finding whether the sentiment of a sentence is positive or negative",
"Reading Comprehension Exam: Answer whether the sentiment of the following sentences is positive or negative.",
"Someone told me you can find out whether the sentiment of a sentence is positive or negative."
"Could you be a dear and tell me whether the sentence's sentiment is negative or positive?",
"I need to find out whether this sentence's sentiment is positive or negative.",
"I need to know whether this sentence's sentiment is negative or positive.",
"You are a genius at telling whether the sentiment of a sentence is negative or positive",
"Reading Comprehension Exam: Answer whether the sentiment of the following sentences is negative or positive.",
"College Preparatory Exam (Reading Comprehension): Identify whether the following sentence is negative or positive in sentiment.",
"Could you tell me whether the sentiment of this sentence is negative or positive?",
"College Preparatory Exam (Reading Comprehension): Answer whether the sentiment of the following sentences is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Identify whether the sentiment of the following sentences is negative or positive.",
"I want to know if the sentiment of the sentence is negative or positive.",
"I've heard you're really good at finding out if a sentence's sentiment is positive or negative."
"Could you tell me whether the sentiment of the sentence is negative or positive?",
"College Preparatory Exam (Reading Comprehension): Identify whether the sentiment of the following sentences is positive or negative.",
"Reading Comprehension Exam: Tell whether the sentiment of the sentence is positive or negative.",
"Can you check whether the sentiment of the sentence is negative or positive?",
"You are a genius at telling if a sentence's sentiment is positive or negative",
"Indicate if the sentiment of this sentence is negative or positive.",
"Could you be a dear and tell me if the sentiment of the sentence is negative or positive?",
"Be a dear and tell me whether this sentence's sentiment is positive or negative, will you?",
"I need to find out whether the sentiment of this sentence is negative or positive.",
"Can you check if the sentiment of the sentence is positive or negative?",
"Be a dear and tell me if this sentence's sentiment is negative or positive, will you?",
"I've heard you're really good at telling whether a sentence's sentiment is negative or positive."
"Tell if the sentiment of this sentence is positive or negative.",
"I want to know whether this sentence's sentiment is positive or negative.",
"Would you be a dear and check whether the sentence's sentiment is negative or positive?",
"College Preparatory Exam (Reading Comprehension): Answer whether the sentiment of the sentence is negative or positive.",
"Could you be a dear and tell me whether this sentence's sentiment is negative or positive?",
"Are you able to check whether the sentiment of the sentence is positive or negative?",
"I want to learn whether this sentence's sentiment is positive or negative.",
"You are a genius at telling if a sentence's sentiment is negative or positive",
"College Preparatory Exam (Reading Comprehension): Answer whether the sentiment of the sentences is negative or positive.",
"Indicate if the sentiment is positive or negative.",
"You are an expert at finding if the sentiment of a sentence is positive or negative",
"I want to learn if the sentiment of the sentence is negative or positive.",
"Would you be a dear and check if this sentence's sentiment is positive or negative?",
"Can you check if this sentence's sentiment is negative or positive?",
"Analysis of sentiment (negative/positive) task",
"I want to find out if the sentiment of this sentence is positive or negative.",
"Could you be a dear and check if the sentiment of the sentence is positive or negative?",
"English Reading Comprehension Exam: Identify whether the sentences are positive or negative in sentiment.",
"Be a dear and tell me whether this sentence's sentiment is negative or positive, will you?",
"Reading Comprehension Exam: Identify whether the following sentences are positive or negative in sentiment.",
"Could you be a dear and tell me whether the sentiment of this sentence is positive or negative?",
"Would you be a dear and tell me if this sentence's sentiment is negative or positive?",
"I want to know whether the sentiment of this sentence is positive or negative.",
"I need to learn if this sentence's sentiment is positive or negative.",
"Be a dear and check if the sentiment of this sentence is negative or positive, will you?",
"English Reading Comprehension Exam: Tell whether the sentiment of the following sentences is negative or positive.",
"Sentiment understanding task (positive/negative)",
"College Preparatory Exam (Reading Comprehension): Tell whether the sentences are negative or positive in sentiment.",
"Be a dear and tell me if the sentence's sentiment is negative or positive, will you?",
"Just tell me this sentence's sentiment!",
"Sentiment analysis task (negative/positive)",
"Clarify if the sentiment of the sentence is negative or positive.",
"Tell me the sentiment!",
"Be a dear and check if the sentiment of this sentence is positive or negative, will you?",
"English Reading Comprehension Exam: Identify whether the sentiment of the following sentence is negative or positive.",
"College Preparatory Exam (Reading Comprehension): Answer whether the sentiment of the following sentences is negative or positive.",
"Be a dear and tell me whether the sentiment of this sentence is positive or negative, will you?",
"I need to find out if the sentiment of the sentence is positive or negative.",
"English Reading Comprehension Exam: Tell whether the following sentence is positive or negative in sentiment.",
"Comprehension (negative/positive) of sentiment task",
"Indicate if the sentiment of the sentence is negative or positive.",
"College Preparatory Exam (Reading Comprehension): Tell whether the sentence is positive or negative in sentiment.",
"Can you check if the sentiment of the sentence is negative or positive?",
"I want to learn if the sentiment of this sentence is negative or positive.",
"English Reading Comprehension Exam: Answer whether the sentiment of the sentence is negative or positive.",
"I've heard you can find out if the sentiment of a sentence is positive or negative."
"Could you be a dear and check whether the sentiment of this sentence is positive or negative?",
"Reading Comprehension Exam: Tell whether the sentiment of the sentence is negative or positive.",
"Can you check if the sentiment of this sentence is positive or negative?",
"Reading Comprehension Exam: Answer whether the sentences are positive or negative in sentiment.",
"I want to find out if the sentiment of this sentence is negative or positive.",
"Are you able to tell me whether the sentiment of this sentence is negative or positive?",
"Reading Comprehension Exam: Identify whether the following sentence is positive or negative in sentiment.",
"I've heard you're really good at finding out whether a sentence's sentiment is positive or negative."
"Reading Comprehension Exam: Identify whether the sentences are positive or negative in sentiment.",
"Could you tell me if the sentence's sentiment is positive or negative?",
"Are you able to check if this sentence's sentiment is negative or positive?",
"Reading Comprehension Exam: Tell whether the sentiment of the sentences is negative or positive.",
"I want to know whether the sentiment of this sentence is negative or positive.",
"Could you be a dear and check if the sentence's sentiment is negative or positive?",
"Be a dear and tell me whether the sentiment of the sentence is negative or positive, will you?",
"Could you be a dear and tell me if this sentence's sentiment is positive or negative?",
"I need to learn whether the sentence's sentiment is positive or negative.",
"Would you be a dear and check if the sentence's sentiment is negative or positive?",
"I need to learn whether this sentence's sentiment is negative or positive.",
"Just tell me the sentiment of the sentence!",
"Would you be a dear and tell me whether the sentiment of the sentence is negative or positive?",
"Tell if the sentiment is positive or negative.",
"I've heard you can find out if a sentence's sentiment is positive or negative."
"College Preparatory Exam (Reading Comprehension): Identify whether the sentiment of the following sentence is negative or positive.",
"Are you able to tell me if the sentiment of the sentence is positive or negative?",
"You are a genius at telling whether a sentence's sentiment is positive or negative",
"You are a genius at finding if a sentence's sentiment is negative or positive",
"I've heard you can find out whether the sentiment of a sentence is negative or positive."
"You are a master at finding if the sentiment of a sentence is positive or negative",
"I need to learn if the sentence's sentiment is negative or positive.",
"English Reading Comprehension Exam: Answer whether the sentiment of the sentence is positive or negative.",
"I need to learn if the sentiment of the sentence is negative or positive.",
"Reading Comprehension Exam: Tell whether the sentiment of the sentences is positive or negative.",
"Tell me if the sentence is positive or negative!",
"Clarify if the sentiment is positive or negative.",
"I want to know whether the sentiment of the sentence is negative or positive.",
"Be a dear and check if the sentence's sentiment is positive or negative, will you?",
"English Reading Comprehension Exam: Identify whether the sentiment of the following sentence is positive or negative.",
"I need to learn if the sentiment of the sentence is positive or negative.",
"You are a genius at telling if the sentiment of a sentence is negative or positive",
"Tell if the sentence's sentiment is negative or positive.",
"Could you tell me if this sentence's sentiment is negative or positive?",
"I need to find out whether this sentence's sentiment is negative or positive.",
"Can you tell me whether the sentence's sentiment is negative or positive?",
"Tell whether the sentiment is positive or negative.",
"Someone told me you can find out if the sentiment of a sentence is negative or positive."
"Sentiment (negative/positive) comprehension task",
"English Reading Comprehension Exam: Answer whether the sentiment of the following sentences is negative or positive.",
"Would you be a dear and tell me if this sentence's sentiment is positive or negative?",
"I want to learn if the sentence's sentiment is positive or negative.",
"Reading Comprehension Exam: Answer whether the sentiment of the sentences is positive or negative.",
"You are a genius at finding whether a sentence's sentiment is negative or positive",
"Tell if the sentiment of this sentence is negative or positive.",
"Understanding (negative/positive) of sentiment task",
"Comprehension (positive/negative) of sentiment task",
"Are you able to check if the sentiment of the sentence is positive or negative?",
"Would you be a dear and tell me whether the sentence's sentiment is positive or negative?",
"Someone told me you can tell whether the sentiment of a sentence is positive or negative."
"I need to find out if the sentiment of this sentence is positive or negative.",
"Be a dear and tell me if the sentiment of this sentence is positive or negative, will you?",
"Could you check if the sentiment of the sentence is negative or positive?",
"I've heard you're really good at finding out if a sentence's sentiment is negative or positive."
"Sentiment understanding (positive/negative) task",
"English Reading Comprehension Exam: Answer whether the following sentence is positive or negative in sentiment.",
"Indicate if the sentence is negative or positive.",
"College Preparatory Exam (Reading Comprehension): Identify whether the sentence is positive or negative in sentiment.",
"Indicate if the sentiment is negative or positive.",
"Are you able to tell me whether the sentiment of this sentence is positive or negative?",
"English Reading Comprehension Exam: Identify whether the sentiment of the sentence is positive or negative.",
"Understanding of sentiment (negative/positive) task",
"Indicate if the sentence's sentiment is negative or positive.",
"Can you tell me if the sentence's sentiment is positive or negative?",
"Tell me if the sentiment is negative or positive!",
"Indicate if this sentence's sentiment is negative or positive.",
"Reading Comprehension Exam: Identify whether the following sentences are negative or positive in sentiment.",
"Could you be a dear and check if the sentiment of the sentence is negative or positive?",
"I want to find out if this sentence's sentiment is negative or positive.",
"I've heard you're really good at finding out whether a sentence's sentiment is negative or positive."
"College Preparatory Exam (Reading Comprehension): Tell whether the following sentence is positive or negative in sentiment.",
"Be a dear and check whether the sentence's sentiment is positive or negative, will you?",
"Tell if this sentence's sentiment is negative or positive.",
"I need to know if this sentence's sentiment is negative or positive.",
"Could you check whether the sentiment of this sentence is negative or positive?",
"You are an expert at telling if the sentiment of a sentence is negative or positive",
"Could you tell me if the sentence's sentiment is negative or positive?",
"Just tell me if the sentence is negative or positive!",
"Are you able to check whether this sentence's sentiment is negative or positive?",
"Sentiment comprehension (positive/negative) task",
"Indicate if the sentence's sentiment is positive or negative.",
"Are you able to check if the sentiment of this sentence is positive or negative?",
"I need to find out if the sentiment of this sentence is negative or positive.",
"Tell if this sentence's sentiment is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Tell whether the sentences are positive or negative in sentiment.",
"Indicate if the sentence is positive or negative.",
"I want to find out whether the sentiment of the sentence is negative or positive.",
"I've heard you can tell if a sentence's sentiment is positive or negative."
"Clarify whether the sentiment of the sentence is negative or positive.",
"Clarify whether this sentence's sentiment is negative or positive.",
"I've heard you can tell if a sentence's sentiment is negative or positive."
"Reading Comprehension Exam: Answer whether the sentence is positive or negative in sentiment.",
"Clarify if the sentiment of the sentence is positive or negative.",
"Indicate whether the sentence is negative or positive.",
"I need to learn if this sentence's sentiment is negative or positive.",
"Clarify whether the sentence's sentiment is negative or positive.",
"You are a master at telling whether a sentence's sentiment is positive or negative",
"I need to find out if the sentence's sentiment is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Answer whether the sentence is positive or negative in sentiment.",
"Clarify whether the sentence is positive or negative.",
"Understanding (positive/negative) of sentiment task",
"Could you check whether this sentence's sentiment is positive or negative?",
"Tell if the sentiment of the sentence is positive or negative.",
"Reading Comprehension Exam: Identify whether the sentiment of the following sentences is positive or negative.",
"I've heard you're really good at telling whether the sentiment of a sentence is positive or negative."
"I want to find out if the sentiment of the sentence is negative or positive.",
"You are a master at finding if the sentiment of a sentence is negative or positive",
"Sentiment comprehension task (positive/negative)",
"Would you be a dear and check if the sentiment of the sentence is negative or positive?",
"Can you check whether the sentiment of the sentence is positive or negative?",
"English Reading Comprehension Exam: Answer whether the sentence is negative or positive in sentiment.",
"I want to find out whether the sentiment of this sentence is positive or negative.",
"Could you be a dear and check whether the sentence's sentiment is negative or positive?",
"I've heard you're really good at telling if the sentiment of a sentence is positive or negative."
"I need to know if the sentiment of this sentence is negative or positive.",
"English Reading Comprehension Exam: Identify whether the following sentence is positive or negative in sentiment.",
"I want to find out whether the sentiment of this sentence is negative or positive.",
"Reading Comprehension Exam: Answer whether the sentiment of the sentence is negative or positive.",
"Could you be a dear and check if the sentence's sentiment is positive or negative?",
"You are a master at finding whether the sentiment of a sentence is negative or positive",
"Are you able to tell me if the sentiment of the sentence is negative or positive?",
"I need to find out if the sentiment of the sentence is negative or positive.",
"Sentiment comprehension task (negative/positive)",
"Reading Comprehension Exam: Answer whether the sentences are negative or positive in sentiment.",
"Would you be a dear and check if this sentence's sentiment is negative or positive?",
"I want to know whether the sentence's sentiment is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Answer whether the sentiment of the following sentence is negative or positive.",
"Could you check whether the sentiment of this sentence is positive or negative?",
"I've heard you're really good at finding out whether the sentiment of a sentence is negative or positive."
"English Reading Comprehension Exam: Tell whether the sentences are negative or positive in sentiment.",
"Clarify whether the sentiment of this sentence is negative or positive.",
"Could you be a dear and check whether this sentence's sentiment is positive or negative?",
"Clarify whether this sentence's sentiment is positive or negative.",
"I want to find out whether the sentence's sentiment is negative or positive.",
"Be a dear and check if this sentence's sentiment is positive or negative, will you?",
"Can you tell me whether the sentence's sentiment is positive or negative?",
"Can you tell me whether this sentence's sentiment is positive or negative?",
"Can you check whether the sentence's sentiment is positive or negative?",
"Are you able to check whether the sentence's sentiment is positive or negative?",
"I need to learn whether the sentiment of the sentence is positive or negative.",
"Indicate whether the sentence's sentiment is positive or negative.",
"You are an expert at finding whether a sentence's sentiment is positive or negative",
"Someone told me you can tell if the sentiment of a sentence is negative or positive."
"I've heard you're really good at finding out if the sentiment of a sentence is negative or positive."
"Clarify if the sentiment is negative or positive.",
"English Reading Comprehension Exam: Answer whether the following sentence is negative or positive in sentiment.",
"Tell whether the sentence's sentiment is negative or positive.",
"You are a master at telling whether the sentiment of a sentence is negative or positive",
"Can you check if the sentiment of this sentence is negative or positive?",
"Reading Comprehension Exam: Answer whether the sentiment of the sentence is positive or negative.",
"College Preparatory Exam (Reading Comprehension): Identify whether the sentiment of the sentence is negative or positive.",
"Clarify if this sentence's sentiment is positive or negative.",
"Are you able to check whether this sentence's sentiment is positive or negative?",
"Could you check if the sentiment of this sentence is positive or negative?",
"English Reading Comprehension Exam: Answer whether the sentiment of the following sentence is positive or negative.",
"Can you check if this sentence's sentiment is positive or negative?",
"I want to learn if the sentiment of this sentence is positive or negative.",
"Sentiment analysis (negative/positive) task",
"Can you tell me if the sentiment of this sentence is positive or negative?",
"Could you tell me whether this sentence's sentiment is positive or negative?",
"Be a dear and check if the sentiment of the sentence is negative or positive, will you?",
"Would you be a dear and check if the sentiment of the sentence is positive or negative?",
"Could you check whether the sentence's sentiment is positive or negative?",
"Someone told me you can tell if a sentence's sentiment is negative or positive."
"Are you able to tell me whether the sentence's sentiment is negative or positive?",
"I need to find out whether the sentence's sentiment is negative or positive.",
"Tell if the sentence is negative or positive.",
"Clarify whether the sentence is negative or positive.",
"You are a genius at telling whether the sentiment of a sentence is positive or negative",
"Could you be a dear and check whether the sentiment of this sentence is negative or positive?",
"Indicate whether the sentiment of this sentence is positive or negative.",
"Can you tell me if this sentence's sentiment is negative or positive?",
"I need to find out if this sentence's sentiment is negative or positive.",
"I need to find out if this sentence's sentiment is positive or negative.",
"Clarify if this sentence's sentiment is negative or positive.",
"Could you be a dear and tell me if the sentence's sentiment is negative or positive?",
"Can you tell me if the sentiment of the sentence is positive or negative?",
"Could you be a dear and check whether this sentence's sentiment is negative or positive?",
"You are a master at finding whether a sentence's sentiment is negative or positive",
"You are an expert at finding whether the sentiment of a sentence is positive or negative",
"Are you able to check if the sentiment of the sentence is negative or positive?",
"Just tell me if the sentence is positive or negative!",
"Are you able to check whether the sentence's sentiment is negative or positive?",
"Clarify whether the sentiment of the sentence is positive or negative.",
"Reading Comprehension Exam: Tell whether the sentiment of the following sentence is positive or negative.",
"Reading Comprehension Exam: Identify whether the sentiment of the following sentence is negative or positive.",
"Sentiment (negative/positive) analysis task",
"English Reading Comprehension Exam: Answer whether the sentences are negative or positive in sentiment.",
"I want to know if the sentiment of the sentence is positive or negative.",
"I need to learn whether this sentence's sentiment is positive or negative.",
"Could you be a dear and tell me whether the sentiment of this sentence is negative or positive?",
"Sentiment (positive/negative) comprehension task",
"I need to know if the sentence's sentiment is positive or negative.",
"Be a dear and tell me if this sentence's sentiment is positive or negative, will you?",
"College Preparatory Exam (Reading Comprehension): Tell whether the sentence is negative or positive in sentiment.",
"Can you check if the sentence's sentiment is negative or positive?",
"You are an expert at finding if a sentence's sentiment is positive or negative",
"Tell whether the sentiment of this sentence is positive or negative.",
"English Reading Comprehension Exam: Answer whether the following sentences are negative or positive in sentiment.",
"Reading Comprehension Exam: Tell whether the sentences are positive or negative in sentiment.",
"Be a dear and check whether the sentence's sentiment is negative or positive, will you?",
"Would you be a dear and tell me whether this sentence's sentiment is negative or positive?",
"Indicate whether the sentiment of this sentence is negative or positive.",
"I've heard you're really good at telling whether a sentence's sentiment is positive or negative."
"College Preparatory Exam (Reading Comprehension): Tell whether the sentiment of the sentence is positive or negative.",
"Would you be a dear and tell me whether the sentence's sentiment is negative or positive?",
"Can you tell me if this sentence's sentiment is positive or negative?",
"I want to know whether this sentence's sentiment is negative or positive.",
"College Preparatory Exam (Reading Comprehension): Identify whether the sentiment of the sentence is positive or negative.",
"Could you check whether the sentiment of the sentence is negative or positive?",
"I need to find out whether the sentiment of this sentence is positive or negative.",
"Could you check if the sentence's sentiment is negative or positive?",
"I've heard you can find out if a sentence's sentiment is negative or positive."
"Tell whether the sentence is negative or positive.",
"Could you check whether the sentence's sentiment is negative or positive?",
"English Reading Comprehension Exam: Identify whether the sentences are negative or positive in sentiment.",
"I need to know whether the sentiment of the sentence is positive or negative.",
"Reading Comprehension Exam: Identify whether the sentiment of the following sentences is negative or positive.",
"English Reading Comprehension Exam: Tell whether the sentence is positive or negative in sentiment.",
"I've heard you can tell whether a sentence's sentiment is positive or negative."
"College Preparatory Exam (Reading Comprehension): Tell whether the sentiment of the sentences is negative or positive.",
"Analysis of sentiment (positive/negative) task",
"I've heard you can find out whether a sentence's sentiment is positive or negative."
"College Preparatory Exam (Reading Comprehension): Answer whether the following sentences are positive or negative in sentiment.","""

engine = 'davinci'
batch_size = 500
max_attempts = 100

new_lines, repeated_lines = generate_no_verbatim(prompt=prompt2, temperature=1, engine=engine, scramble=True,
                                                 prepend_string='List of different ways to prompt whether the sentiment of a sentence is positive or negative:\n', max_attempts=max_attempts)

print('new lines: ', '\n'.join(new_lines))
print('# repeated lines: ', len(repeated_lines))

f = open(f"new_sentiment_prompts_single-line-prepend-{engine}-{max_attempts}-attempts.txt", "a")
f.write('\n'.join(new_lines))
f.close()


